module Test.Examples.ColorRing where

import Transit (type (:*), type (:@), type (>|), Empty, Transit)
import Type.Function (type ($))

type ColorTest = Transit $ Empty
  :* ("StateA" :@ "MsgA" >| "StateB")
  :* ("StateB" :@ "MsgB" >| "StateC")
  :* ("StateC" :@ "MsgC" >| "StateD")
  :* ("StateD" :@ "MsgD" >| "StateE")
  :* ("StateE" :@ "MsgE" >| "StateF")
  :* ("StateF" :@ "MsgF" >| "StateG")
  :* ("StateG" :@ "MsgG" >| "StateH")
  :* ("StateH" :@ "MsgH" >| "StateI")
  :* ("StateI" :@ "MsgI" >| "StateJ")
  :* ("StateJ" :@ "MsgJ" >| "StateK")
  :* ("StateK" :@ "MsgK" >| "StateL")
  :* ("StateL" :@ "MsgL" >| "StateM")
  :* ("StateM" :@ "MsgM" >| "StateN")
  :* ("StateN" :@ "MsgN" >| "StateO")
  :* ("StateO" :@ "MsgO" >| "StateP")
  :* ("StateP" :@ "MsgP" >| "StateQ")
  :* ("StateQ" :@ "MsgQ" >| "StateR")
  :* ("StateR" :@ "MsgR" >| "StateS")
  :* ("StateS" :@ "MsgS" >| "StateT")
  :* ("StateT" :@ "MsgT" >| "StateU")
  :* ("StateU" :@ "MsgU" >| "StateV")
  :* ("StateV" :@ "MsgV" >| "StateW")
  :* ("StateW" :@ "MsgW" >| "StateX")
  :* ("StateX" :@ "MsgX" >| "StateY")
  :* ("StateY" :@ "MsgY" >| "StateZ")

